service:
  name: web-otp-demo-api
custom:
  defaultStage: dev
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  profile: aa
  stage: ${opt:stage, self:custom.defaultStage}
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'sns:Publish'
      Resource: '*'
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    AUTH_KEY: ${env:AUTH_KEY}
functions:
  authorizerFunc:
    handler: handler.auth
  sendSMS:
    handler: handler.sendSMS
    events:
      - http:
          method: post
          path: sendSMS
          authorizer: authorizerFunc
          cors: true
